#!/bin/sh
set -efu

export LC_ALL=C.UTF-8

pys="$(pyversions -rv 2> /dev/null)"

cp -a tests "$ADTTMP"
cd "$ADTTMP"

for py in $pys; do
	echo "=== python$py ==="
	python$py -m unittest discover tests/ 2>&1
done
